Repository CaedenPH/Jarvide, pull requests merged in 2022-01, with the labels that each got.

#75 Commenting test from templates MD
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/review-policy.yml
  .pre-commit-config.yaml
Labels: suggestion

#82 Fixed missing brackets
  src/bot.py
  src/cogs/fun.py
Labels: bug

#85 Improvement in Error Handling , Fixed Help Command , Made reason for Unban command not required
  src/bot.py
  src/cogs/errors.py
  src/cogs/help.py
  src/cogs/mod.py
Labels: enhancement

#86 Fixed everything
  src/bot.py
  src/cogs/ide/auto_detect.py
Labels: bug

#76 make a ToS
  TOS.md
Labels: documentation

#102 API connection base code and reformat of code
  .example-env
  requirements.txt
  src/bot.py
  src/cogs/config.py
  src/cogs/errors.py
  src/cogs/fun.py
  src/cogs/help.py
  src/cogs/ide/auto_detect.py
  src/cogs/ide/dialogs/edit_view.py
  src/cogs/ide/dialogs/file_view.py
  src/cogs/ide/dialogs/navigated_saved.py
  src/cogs/ide/dialogs/open_view.py
  src/cogs/ide/ide.py
  src/cogs/misc.py
  src/cogs/mod.py
  src/cogs/staff.py
  src/utils/utils.py
  tox.ini
Labels: enhancement
